with-expecter: true
packages:
  github.com/nawafswe/orders-service/pkg/v1:
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      OrderRepo:
        # Modify package-level config for this specific interface (if applicable)
#        config:

      OrderUseCase:

  github.com/nawafswe/orders-service/pkg/messaging:
    config:
    interfaces:
      MessageService:

  github.com/nawafswe/orders-service/pkg/logger:
    config:
    interfaces:
        Logger: