// Code generated by mockery v2.40.1. DO NOT EDIT.

package v1

import (
	context "context"

	models "github.com/nawafswe/orders-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderUseCase is an autogenerated mock type for the OrderUseCase type
type MockOrderUseCase struct {
	mock.Mock
}

type MockOrderUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderUseCase) EXPECT() *MockOrderUseCase_Expecter {
	return &MockOrderUseCase_Expecter{mock: &_m.Mock}
}

// HandleOrderApproval provides a mock function with given fields: ctx
func (_m *MockOrderUseCase) HandleOrderApproval(ctx context.Context) {
	_m.Called(ctx)
}

// MockOrderUseCase_HandleOrderApproval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleOrderApproval'
type MockOrderUseCase_HandleOrderApproval_Call struct {
	*mock.Call
}

// HandleOrderApproval is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderUseCase_Expecter) HandleOrderApproval(ctx interface{}) *MockOrderUseCase_HandleOrderApproval_Call {
	return &MockOrderUseCase_HandleOrderApproval_Call{Call: _e.mock.On("HandleOrderApproval", ctx)}
}

func (_c *MockOrderUseCase_HandleOrderApproval_Call) Run(run func(ctx context.Context)) *MockOrderUseCase_HandleOrderApproval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOrderUseCase_HandleOrderApproval_Call) Return() *MockOrderUseCase_HandleOrderApproval_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderUseCase_HandleOrderApproval_Call) RunAndReturn(run func(context.Context)) *MockOrderUseCase_HandleOrderApproval_Call {
	_c.Call.Return(run)
	return _c
}

// HandleOrderRejection provides a mock function with given fields: ctx
func (_m *MockOrderUseCase) HandleOrderRejection(ctx context.Context) {
	_m.Called(ctx)
}

// MockOrderUseCase_HandleOrderRejection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleOrderRejection'
type MockOrderUseCase_HandleOrderRejection_Call struct {
	*mock.Call
}

// HandleOrderRejection is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrderUseCase_Expecter) HandleOrderRejection(ctx interface{}) *MockOrderUseCase_HandleOrderRejection_Call {
	return &MockOrderUseCase_HandleOrderRejection_Call{Call: _e.mock.On("HandleOrderRejection", ctx)}
}

func (_c *MockOrderUseCase_HandleOrderRejection_Call) Run(run func(ctx context.Context)) *MockOrderUseCase_HandleOrderRejection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockOrderUseCase_HandleOrderRejection_Call) Return() *MockOrderUseCase_HandleOrderRejection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderUseCase_HandleOrderRejection_Call) RunAndReturn(run func(context.Context)) *MockOrderUseCase_HandleOrderRejection_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceOrder provides a mock function with given fields: ctx, order
func (_m *MockOrderUseCase) PlaceOrder(ctx context.Context, order models.Order) (models.Order, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for PlaceOrder")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) (models.Order, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) models.Order); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Order) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderUseCase_PlaceOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceOrder'
type MockOrderUseCase_PlaceOrder_Call struct {
	*mock.Call
}

// PlaceOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.Order
func (_e *MockOrderUseCase_Expecter) PlaceOrder(ctx interface{}, order interface{}) *MockOrderUseCase_PlaceOrder_Call {
	return &MockOrderUseCase_PlaceOrder_Call{Call: _e.mock.On("PlaceOrder", ctx, order)}
}

func (_c *MockOrderUseCase_PlaceOrder_Call) Run(run func(ctx context.Context, order models.Order)) *MockOrderUseCase_PlaceOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Order))
	})
	return _c
}

func (_c *MockOrderUseCase_PlaceOrder_Call) Return(_a0 models.Order, _a1 error) *MockOrderUseCase_PlaceOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderUseCase_PlaceOrder_Call) RunAndReturn(run func(context.Context, models.Order) (models.Order, error)) *MockOrderUseCase_PlaceOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function with given fields: ctx, orderId, status
func (_m *MockOrderUseCase) UpdateOrderStatus(ctx context.Context, orderId int64, status string) (models.Order, error) {
	ret := _m.Called(ctx, orderId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (models.Order, error)); ok {
		return rf(ctx, orderId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) models.Order); ok {
		r0 = rf(ctx, orderId, status)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, orderId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderUseCase_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderUseCase_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId int64
//   - status string
func (_e *MockOrderUseCase_Expecter) UpdateOrderStatus(ctx interface{}, orderId interface{}, status interface{}) *MockOrderUseCase_UpdateOrderStatus_Call {
	return &MockOrderUseCase_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, orderId, status)}
}

func (_c *MockOrderUseCase_UpdateOrderStatus_Call) Run(run func(ctx context.Context, orderId int64, status string)) *MockOrderUseCase_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockOrderUseCase_UpdateOrderStatus_Call) Return(_a0 models.Order, _a1 error) *MockOrderUseCase_UpdateOrderStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderUseCase_UpdateOrderStatus_Call) RunAndReturn(run func(context.Context, int64, string) (models.Order, error)) *MockOrderUseCase_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderUseCase creates a new instance of MockOrderUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderUseCase {
	mock := &MockOrderUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
